UI:
  - changed-files:
      - any-glob-to-any-file:
          - "application/ui/**/*"

Backend:
  - changed-files:
      - any-glob-to-any-file:
          - "application/backend/**/*"

Trainer:
  - changed-files:
      - any-glob-to-any-file:
          - "application/trainer/**/*"

Application:
  - changed-files:
      - any-glob-to-any-file:
          - "application/**/*"

Library:
  - changed-files:
      - any-glob-to-any-file:
          - "library/**/*"
