import createFetchClient from 'openapi-fetch';
import createClient from 'openapi-react-query';

import { createPathHelper } from './client-path';
import type { paths } from './openapi-spec'; // generated by openapi-typescript

export const API_BASE_URL = '';

export function getClient<Paths extends paths>({ baseUrl }: { baseUrl: string }) {
    const fetchClient = createFetchClient<Paths>({ baseUrl });

    return {
        ...fetchClient,
        PATH: createPathHelper<Paths>(baseUrl),
    };
}

export const fetchClient = getClient({
    baseUrl: (typeof process !== 'undefined' ? process.env.PUBLIC_API_BASE_URL : undefined) ?? API_BASE_URL,
});

export const $api = createClient(fetchClient);
