name: "Pull Request Labeler"
on:
  pull_request_target:
    types:
      - opened
      - synchronize
      # The labeler doesn't checkout/execute any contributed code, so it should be safe.
      - reopened # zizmor: ignore[dangerous-triggers]

permissions: {}

concurrency:
  group: labeler-${{ github.workflow }}-${{ github.event.pull_request.number || github.run_id }}
  cancel-in-progress: true

jobs:
  label:
    permissions:
      contents: read # Read label configuration from repository
      pull-requests: write # Apply labels on pull requests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/labeler@f27b608878404679385c85cfa523b85ccb86e213 # v6.1.0
