name: TruffleHog Secret Scan

permissions: {} # No permissions by default on workflow level

on:
  workflow_dispatch:
  push:
  pull_request:

concurrency:
  group: backend-${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  secret-scan:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Harden the runner
        uses: step-security/harden-runner@bf7454d06d71f1098171f2acdf0cd4708d7b5920 # v2.20.0
        with:
          disable-sudo: true
          disable-telemetry: true
          egress-policy: block
          allowed-endpoints: >
            api.sonarcloud.io:443
            app.eraser.io:443
            ghcr.io:443
            github.com:443
            pkg-containers.githubusercontent.com:443
            sonarcloud.io:443
            api.github.com:443
            auth.docker.io:443
            registry.npmjs.org:443
            upload.pypi.org:443
      - name: Checkout code
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Secret Scanning
        uses: trufflesecurity/trufflehog@00155c9dc586f34d189adc83d3ac2698c2ec551f # v3.95.8
        with:
          extra_args: --results=verified,unknown --exclude-paths=.trufflehogignore
